[project]
name = "beauthy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "dotenv>=0.9.9",
    "ollama>=0.6.0",
    "pygithub>=2.8.1",
    "requests>=2.32.5",
]
